version: '3'

services:
  flask-server: 
    build: .
    ports: 
      - '5000:5000'
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    environment:
      - discovery.type=single-node
  nginx:
    build: flask-app/Proxy
    ports:
      - '4000:4000'
 